### ISSUE TITLE
تحسين طريقة العمل

### ISSUE THREAD

**Issue by chadidi** [LaravelArab/docs#12]
<div dir="rtl">
من الأن وصاعدا علينا العمل على أخر فرع 5.4 في الوقت الحالي و كل ملف ننتهي من ترجمته ندمجه مع master
</div>

**Comment by atefBB** [comment]
<div dir="rtl">عُـلم !</div>

**Comment by chadidi** [comment]
<div dir="rtl">
@atefBB بالنسبة لخاصية RTL سيتم عملها بCSS لذالك ليس من الضرورة إضافة الإتجاه للHTML
