### ISSUE TITLE
installation.md

### ISSUE THREAD

**Issue by chadidi** [LaravelArab/docs#14]
This issue opened to complete this file `installation.md` translation

**Comment by atefBB** [comment]
<div dir="rtl">
@chadidi هل يحتاج الملف إلى مراجعة؟
<br>أظن أن الترجمة فيه مكتملة.
</div>

**Comment by chadidi** [comment]
نعم لقد تم إكمالها لكنني لم أقم بعمل مراجعة ربما لاحقا @atefBB بالنسبة [للملف التالي الخاص بك](https://github.com/LaravelArab/docs/projects/1#card-3996052) الذي عليك ترجمته

**Comment by atefBB** [comment]
<div dir="rtl">هل تمت مراجعة الملف المترجم؟</div>
