### ISSUE TITLE
homestead.md

### ISSUE THREAD

**Issue by chadidi** [LaravelArab/docs#17]
This issue opened to complete this file `homestead.md` translation

**Comment by atefBB** [comment]
@hamza-mostafa @engAhmad @chadidi هل مازلتم تشتغلون على المشروع؟

**Comment by chadidi** [comment]
@atefBB مشغول حاليا ولكن  سأساهم عندما تتاح الفرصة

**Comment by atefBB** [comment]
نسأل الله التوفيق

**Comment by hamza-mostafa** [comment]
سامحونا على التقصير يا جماعة لكن فعلا مشغول .. نسألكم الدعاء
والله يوفق الجميع

**Comment by atefBB** [comment]
@hamza-mostafa وفقكم الله

**Comment by engAhmad** [comment]
@atefBB للاسف مشغول بنظام وموقع الكتروني ولا اجد الا ساعتين في اليوم عمل حتى انهي ما بدأته والتزم مع الزبون
لكن امل ان يتم المشروع على خير والشروع بتعريبات اخرى كون المحتوى العربي يحتاج لدعم
