### ISSUE TITLE
Add 5.7 branch

### ISSUE THREAD

**Issue by chadidi** [LaravelArab/docs#22]
@hamza-mostafa I have merged 5.7 branch to the main repo and deleted the one you forked.

**Comment by hamza-mostafa** [comment]
@chadidi better .. I was worried I might clear the progress of the older repo, so I forked a new one .. I'm continuing this project .. hope to finish before 5.8

**Comment by atefBB** [comment]
@hamza-mostafa @chadidi هل مازال العمل على المشروع جاريا؟

**Comment by chadidi** [comment]
@atefBB نعم
