### ISSUE TITLE
مشروع جميل 

### ISSUE THREAD

**Issue by engAhmad** [LaravelArab/docs#4]
تحياتي شباب اشكر كل القائمين على المشروع الخاص بترجمة اطار العمل لارفيل للعربية وذلك دعما للمحتوى العربي التقني في هذا المجال , وبدوري وبحسب خبرتي المتواضعه اود المشاركه ايضا لكن التحدى الحقيقي الذي اواجهه الان هو ترجمه المصطلحات الى العربيه فكلنا كمبرمجين نتداولها بلغتها الام الانجليزيه فما الحل برائيكم ؟

**Comment by chadidi** [comment]
بالنسبة للمصطلحات فيجب أن تبقى باللغة الأم حسب رأيي لأنها ولو كانت بالإنجليزية فهي في غالب الأحيان تفعل شيئا مختلفا عن المعنى بالإنجليزية أما الباقي فيجب ترجمته.

**Comment by engAhmad** [comment]
اشكرك مع امنياتي للجميع بالتوفيق والسداد

**Comment by chadidi** [comment]
هل تريد أن تنظم لفريق الترجمة؟

**Comment by engAhmad** [comment]
بالطبع

**Comment by chadidi** [comment]
لقد قمت بإرسال الدعوة

**Comment by engAhmad** [comment]
http://ojuba.org/%D8%AA%D8%B1%D8%AC%D9%85%D8%A9_%D8%A7%D9%84%D9%85%D8%B5%D8%B7%D9%84%D8%AD%D8%A7%D8%AA

https://www.arabeyes.org/%D8%A7%D9%84%D9%82%D8%A7%D9%85%D9%88%D8%B3_%D8%A7%D9%84%D8%AA%D9%82%D9%86%D9%8A
